#!/usr/bin/env Rscript
library(optparse)

dr.str = "

▓█████▄   ██▀███  ██   ██▓ ▄████▄   ██▓    ▓█████ ▄▄▄       ███▄    █
 ██▀ ██▌ ▓██   ██  ██  ██  ██▀ ▀█  ▓██▒    ▓█   ▀ ████▄     ██ ▀█   █
░██   █▌ ▓██ ░▄█    ██ ██  ▓█    ▄  ██░    ░███   ██  ▀█▄   ██  ▀█ ██▒
░▓█▄   ▌ ▒██▀▀█▄   ░ ▐██▓ ▒▓▓▄ ▄██▒ ██░    ░▓█  ▄ ██▄▄▄▄█   ██▒  ▐▌██▒
░▒████▓  ░██▓  ██  ░ ██▒    ▓███▀ ░░█████ ▒█████▒ █     █▒ ██░   ▓██░
 ▒ ▓  ▒  ░  ▓ ░▒▓░  ██    ░ ░▒ ▒  ░░ ▒░▓  ░░░ ▒░ ░▒▒   ▓▒█░░ ▒░   ▒ ▒
 ░ ▒  ▒    ░▒ ░  ░  ░░▒░   ░  ▒   ░ ░ ▒  ░ ░ ░  ░ ▒   ▒▒ ░░ ░░   ░ ▒░
 ░ ░  ░    ░░   ░   ░  ░░  ░          ░ ░  ░    ░    ░   ▒      ░   ░ ░
   ░        ░     ░ ░     ░ ░          ░  ░   ░  ░     ░  ░     ░   ░
 ░               ░ ░     ░       ░    ░     ░     ░      ░     ░ 


(Let's dryclean the genomes!)\n"




if (!exists('opt'))
    {
        option_list = list(
            make_option(c("-p", "--pon"), type = "character", help = "Path to Panel Of Normal (PON) on which batch rPCA have been run. Within the file should be L, S matrices, estimated rank for burnin samples and svd decomposition matrices for the same"),
            make_option(c("-i", "--input"), type = "character", help = "Path to cov.rds file, fragCounter output for sample under consideration"),
            make_option(c("-t", "--centered"), type = "logical", default = TRUE, help = "are the samples centered"),
            make_option(c("-s", "--cbs"), type = "logical", default = FALSE, help = "if perform cbs on the drycleaned coverage"),
            make_option(c("-n", "--cnsignif"), type = "integer", default = 1e-5, help = "the significance levels for the test to accept change-points in cbs"),
            make_option(c("-c", "--cores"), type = "integer", default = 10,  help = "How many cores to use"),
            make_option(c("-w", "--wholeGenome"), default = TRUE, type = "logical", help = "If TRUE then it will process all chromosomes and parallelize it"),
            make_option(c("-b", "--blacklist"), default = FALSE, type = "logical", help = "if there are blacklisted makers"),
            make_option(c("-l", "--blacklist_path"), default = NA, type = "character", help = "If use.blacklist == TRUE, path a GRange marking if each marker is set to be excluded or not"),
            make_option(c("-g", "--germline.filter"), default = FALSE, type = "logical", help = "If PON based germline filter is to be used for removing some common germline events, If set to TRUE, give path to germline annotated file"),
            make_option(c("-f", "--germline.file"), default = NA, type = "character", help = "Path to file annotated with germline calls, if germline.filter == TRUE"),
            make_option(c("-m", "--human"), type = "logical", default = TRUE, help = "Specify if the samples under consideration are human"),
            make_option(c("-F", "--field"), type = "character", default = 'reads.corrected', help = "Field name in GRanges metadata to use for drycleaning"),
            make_option(c("-C", "--all.chr"), default = "1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, X", type = "character", help = "list of chromosomes to dryclean"),
            make_option(c("-B", "--build"), type = "character", default = 'hg19', help = "hg19/hg38 build for human samples"),
            make_option(c("-o", "--outdir"), type = "character", default = './', help = "output directory"),
            make_option(c("-T", "--testing"), type = "character", default = FALSE, help = "DO NOT CHANGE"),
            make_option(c("-h", "--help"), action="store_true", default=FALSE, help="Show this help message and exit")

        )

        parseobj = OptionParser(option_list=option_list, add_help_option=FALSE)
        opt = parse_args(parseobj)

        if ((is.null(opt$input)) | is.null(opt$pon))
            stop(print_help(parseobj))

        options(error=function()traceback(2))

        ## keep record of run
        writeLines(paste(paste('--', names(opt), ' ', sapply(opt, function(x) paste(x, collapse = ',')), sep = '', collapse = ' '), sep = ''), paste(opt$outdir, 'cmd.args', sep = '/'))
        saveRDS(opt, paste(opt$outdir, 'cmd.args.rds', sep = '/'))
    }





system(paste('mkdir -p',  opt$outdir))

##############################
#suppressWarnings(suppressPackageStartupMessages(library(dryclean)))
        
        message(dr.str)
        
        suppressWarnings(suppressPackageStartupMessages(devtools::load_all()))
        suppressWarnings(suppressPackageStartupMessages(library(GenomicRanges)))
        
        pon_object <- pon$new(pon_path = opt$pon, build = opt$build)
        
        dryclean_object <- dryclean$new(pon = pon_object)
        
        a <- dryclean_object$clean(
            cov = opt$input, 
            centered = opt$centered, 
            cbs = opt$cbs, 
            cnsignif = opt$cnsignif, 
            mc.cores = opt$cores, 
            verbose = TRUE, 
            whole_genome = opt$wholeGenome, 
            use.blacklist = opt$blacklist, 
            blacklist_path = opt$blacklist_path, 
            germline.filter = opt$germline.filter, 
            germline.file = opt$germline.file, 
            field = opt$field, 
            is.human = opt$human, 
            all.chr = strsplit(opt$all.chr,", ")[[1]],
            testing = opt$testing
        )
        
        this.out = a
        
        saveRDS(this.out, paste0(opt$outdir, 'drycleaned.cov.rds'))
        
        message('Giddy Up!') 

